spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pastebook
    username: pastebookadmin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    disabled: true
    locations: classpath:db/migration
server:
  port: 8080
jwt:
  secret: "someSecretStringByQwerty"
  access_token:
    expiration: 600000  # 10 minutes
  refresh_token:
    expiration: 24 * 60 * 60 * 1000 # 1 day