create table users (
    id bigint generated by default as identity primary key,
    hashed_password varchar(255),
    username varchar(255) constraint uk_username unique
);

alter table users
    owner to pastebookadmin;

create table pastes
(
    hash varchar(255) not null primary key,
    access_modifier varchar(255),
    date_of_creation timestamp,
    expiration timestamp,
    text text,
    title varchar(255) default 'Untitled'::character varying,
    owner_id bigint constraint fk_pastes_to_users references users
);

alter table pastes
    owner to pastebookadmin;

